# Generated by Django 4.2.4 on 2023-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='lol', max_length=200),
            preserve_default=False,
        ),
    ]
