# Generated by Django 4.2.4 on 2023-08-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_end_year_event_start_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member_amt',
            new_name='amount_of_members',
        ),
    ]
