# Generated by Django 4.2.4 on 2023-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_member_amt_team_amount_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trailer',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
