# Generated by Django 4.2.4 on 2023-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_trailer_alter_event_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='position',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
