# Generated by Django 4.2.4 on 2023-08-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_end_year_remove_event_start_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='photos', to='events.photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poster', to='events.photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trailer', to='events.video'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_report', to='events.video'),
        ),
    ]
