# Generated by Django 4.2.4 on 2023-08-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.AddField(
            model_name='event',
            name='photo_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.photoalbum'),
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.photoalbum'),
        ),
    ]
