# Generated by Django 4.2.4 on 2023-08-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_sponsor_url_sponsor_site_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.photoalbum'),
        ),
    ]
