# Generated by Django 4.2.4 on 2023-08-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
