# Generated by Django 4.2.4 on 2023-08-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_trailer_alter_event_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logo', to='events.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.photoalbum'),
        ),
    ]
