# Generated by Django 4.2.4 on 2023-08-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0017_event_logo_alter_photo_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='from_hse',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='university',
            field=models.CharField(default='HSE', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonNotHSE',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='events.eventcategory'),
            preserve_default=False,
        ),
    ]
