# Generated by Django 4.2.4 on 2023-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='where_knew',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
