# Generated by Django 4.2.4 on 2023-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_team_where_knew_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vk_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
