# Generated by Django 4.2.4 on 2023-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_vk_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="captain_email",
            field=models.CharField(default="test@email.ru", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="captain_tg",
            field=models.CharField(default="@testtg", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="university",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.CharField(max_length=200),
        ),
    ]
